FROM alpine:3.7

COPY . /app
WORKDIR /app

RUN apk add --update --no-cache                      \
        gcc g++ gnupg make libffi-dev       \
        openssl-dev uwsgi-python3 python3   \
        python3-dev                         \
        libxslt-dev                         \
    && pip3 install -r requirements.txt

RUN chmod a+rw db_file db_file/*

CMD [ "uwsgi", "--socket", "0.0.0.0:5000",  \
               "--uid", "uwsgi",            \
               "--plugins", "python3",      \
               "--protocol", "http",        \
               "--wsgi", "wsgi:app",         \
                "--master"]

EXPOSE 5000